#!/usr/bin/env python
import subprocess
import sys,os
import smtplib
from config import *

def send_email(message):
	try:
		smtpObj = smtplib.SMTP('localhost')
		smtpObj.sendmail(mail_from, mail_rcpt, message)
	except SMTPException:
		return

days_in_seconds = days * 3600 * 24
for path, subdirs, files in os.walk(root):
    for name in files:
	if name == cert_name:
		openssl = subprocess.Popen(
			("openssl", "x509", "-checkend", "%s"%days_in_seconds, "-in", os.path.join(path, name), "-noout"),
			stdin = subprocess.PIPE,
			stdout = None,
		)
		openssl.communicate('\n'.join(name))
		openssl.wait()
		domain = subprocess.check_output("openssl x509 -noout -subject -in %s/%s | sed -n '/^subject/s/^.*CN=//p'"%(path, name), shell=True)
		if openssl.returncode != 0:
			email += 'Less than %s days to %s cert expiration' %(days, domain)
			continue
		else:
			email += '%s cert expiration date correct'%domain
			continue

send_email(email)
